FROM mcr.microsoft.com/dotnet/aspnet:6.0 AS base
WORKDIR /app

FROM mcr.microsoft.com/dotnet/sdk:6.0 AS build

WORKDIR /src
COPY ["src/Ticketek.Core.Api/Ticketek.Core.Api.csproj", "Ticketek.Core.Api/"]
RUN dotnet restore "Ticketek.Core.Api/Ticketek.Core.Api.csproj"
#Copy all files in the src folder
COPY /src/ /src/
RUN ls -la
WORKDIR "/src/Ticketek.Core.Api"
RUN dotnet build "Ticketek.Core.Api.csproj" -c Release -o /app/build

FROM build AS publish
RUN dotnet publish "Ticketek.Core.Api.csproj" -c Release -o /app/publish

FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

EXPOSE 8080
ENV ASPNETCORE_URLS=http://+:8080
ENTRYPOINT ["dotnet", "Ticketek.Core.Api.dll"]


# Path: src/Reportify.Auth.Api/dockerfile